// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ichphbsznqjdvjdhsgbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljaHBoYnN6bnFqZHZqZGhzZ2JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NzQ1ODgsImV4cCI6MjA2MTE1MDU4OH0.GpKDxpW_yOU2gam3_h2f5pbUxBwGMgWnsI_1s2V48Rw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);